# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtbe/resources/mainwindow.ui'
#
# Created: Sun Aug 14 23:00:12 2011
#      by: pyside-uic 0.2.9 running on PySide 1.0.5
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(971, 646)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mainBox = QtGui.QGroupBox(self.centralwidget)
        self.mainBox.setFlat(False)
        self.mainBox.setObjectName("mainBox")
        self.gridLayout = QtGui.QGridLayout(self.mainBox)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.projectTitle = QtGui.QLabel(self.mainBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectTitle.sizePolicy().hasHeightForWidth())
        self.projectTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.projectTitle.setFont(font)
        self.projectTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.projectTitle.setObjectName("projectTitle")
        self.gridLayout.addWidget(self.projectTitle, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.mainBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.newBugBox = QtGui.QGroupBox(self.layoutWidget)
        self.newBugBox.setObjectName("newBugBox")
        self.newCommentGrid_2 = QtGui.QGridLayout(self.newBugBox)
        self.newCommentGrid_2.setObjectName("newCommentGrid_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.newCommentGrid_2.addItem(spacerItem, 1, 0, 1, 1)
        self.saveBugButton = QtGui.QPushButton(self.newBugBox)
        self.saveBugButton.setObjectName("saveBugButton")
        self.newCommentGrid_2.addWidget(self.saveBugButton, 1, 1, 1, 1)
        self.newBugEdit = QtGui.QLineEdit(self.newBugBox)
        self.newBugEdit.setObjectName("newBugEdit")
        self.newCommentGrid_2.addWidget(self.newBugEdit, 0, 0, 1, 2)
        self.gridLayout_3.addWidget(self.newBugBox, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bugsLabel_3 = QtGui.QLabel(self.layoutWidget)
        self.bugsLabel_3.setObjectName("bugsLabel_3")
        self.horizontalLayout_8.addWidget(self.bugsLabel_3)
        self.bugsLabel = QtGui.QLabel(self.layoutWidget)
        self.bugsLabel.setObjectName("bugsLabel")
        self.horizontalLayout_8.addWidget(self.bugsLabel)
        self.bugFilterCombo = QtGui.QComboBox(self.layoutWidget)
        self.bugFilterCombo.setObjectName("bugFilterCombo")
        self.bugFilterCombo.addItem("")
        self.bugFilterCombo.addItem("")
        self.bugFilterCombo.addItem("")
        self.horizontalLayout_8.addWidget(self.bugFilterCombo)
        self.bugsLabel_2 = QtGui.QLabel(self.layoutWidget)
        self.bugsLabel_2.setObjectName("bugsLabel_2")
        self.horizontalLayout_8.addWidget(self.bugsLabel_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.newBugButton = QtGui.QPushButton(self.layoutWidget)
        self.newBugButton.setCheckable(True)
        self.newBugButton.setObjectName("newBugButton")
        self.horizontalLayout_11.addWidget(self.newBugButton)
        self.removeBugButton = QtGui.QPushButton(self.layoutWidget)
        self.removeBugButton.setEnabled(False)
        self.removeBugButton.setObjectName("removeBugButton")
        self.horizontalLayout_11.addWidget(self.removeBugButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.vcsLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.vcsLabel.setFont(font)
        self.vcsLabel.setText("")
        self.vcsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.vcsLabel.setObjectName("vcsLabel")
        self.horizontalLayout_12.addWidget(self.vcsLabel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 5, 0, 1, 1)
        self.bugTable = QtGui.QTableView(self.layoutWidget)
        self.bugTable.setAlternatingRowColors(True)
        self.bugTable.setSortingEnabled(True)
        self.bugTable.setObjectName("bugTable")
        self.gridLayout_3.addWidget(self.bugTable, 2, 0, 1, 1)
        self.customFilterBox = QtGui.QGroupBox(self.layoutWidget)
        self.customFilterBox.setEnabled(True)
        self.customFilterBox.setObjectName("customFilterBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.customFilterBox)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.customFilterLabel = QtGui.QLabel(self.customFilterBox)
        font = QtGui.QFont()
        font.setItalic(False)
        self.customFilterLabel.setFont(font)
        self.customFilterLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.customFilterLabel.setObjectName("customFilterLabel")
        self.verticalLayout_3.addWidget(self.customFilterLabel)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.propertyCombo = QtGui.QComboBox(self.customFilterBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyCombo.sizePolicy().hasHeightForWidth())
        self.propertyCombo.setSizePolicy(sizePolicy)
        self.propertyCombo.setObjectName("propertyCombo")
        self.propertyCombo.addItem("")
        self.propertyCombo.addItem("")
        self.propertyCombo.addItem("")
        self.propertyCombo.addItem("")
        self.horizontalLayout_14.addWidget(self.propertyCombo)
        self.valueCombo = QtGui.QComboBox(self.customFilterBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueCombo.sizePolicy().hasHeightForWidth())
        self.valueCombo.setSizePolicy(sizePolicy)
        self.valueCombo.setObjectName("valueCombo")
        self.horizontalLayout_14.addWidget(self.valueCombo)
        self.addFilterButton = QtGui.QPushButton(self.customFilterBox)
        self.addFilterButton.setObjectName("addFilterButton")
        self.horizontalLayout_14.addWidget(self.addFilterButton)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.filterBugsButton = QtGui.QPushButton(self.customFilterBox)
        self.filterBugsButton.setObjectName("filterBugsButton")
        self.horizontalLayout_9.addWidget(self.filterBugsButton)
        self.cancelFilterButton = QtGui.QPushButton(self.customFilterBox)
        self.cancelFilterButton.setObjectName("cancelFilterButton")
        self.horizontalLayout_9.addWidget(self.cancelFilterButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addWidget(self.customFilterBox, 1, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.bugTitle = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.bugTitle.setFont(font)
        self.bugTitle.setObjectName("bugTitle")
        self.verticalLayout.addWidget(self.bugTitle)
        self.bugCommentBrowser = QtGui.QTextBrowser(self.layoutWidget1)
        self.bugCommentBrowser.setOpenExternalLinks(True)
        self.bugCommentBrowser.setObjectName("bugCommentBrowser")
        self.verticalLayout.addWidget(self.bugCommentBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.bugDetailsBox = QtGui.QGroupBox(self.layoutWidget1)
        self.bugDetailsBox.setFlat(False)
        self.bugDetailsBox.setCheckable(False)
        self.bugDetailsBox.setObjectName("bugDetailsBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.bugDetailsBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.shortLabel = QtGui.QLabel(self.bugDetailsBox)
        self.shortLabel.setText("")
        self.shortLabel.setObjectName("shortLabel")
        self.gridLayout_2.addWidget(self.shortLabel, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.idLabel = QtGui.QLabel(self.bugDetailsBox)
        self.idLabel.setText("")
        self.idLabel.setObjectName("idLabel")
        self.gridLayout_2.addWidget(self.idLabel, 0, 4, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.statusCombo = QtGui.QComboBox(self.bugDetailsBox)
        self.statusCombo.setObjectName("statusCombo")
        self.horizontalLayout_4.addWidget(self.statusCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.severityCombo = QtGui.QComboBox(self.bugDetailsBox)
        self.severityCombo.setObjectName("severityCombo")
        self.horizontalLayout_5.addWidget(self.severityCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.targetCombo = QtGui.QComboBox(self.bugDetailsBox)
        self.targetCombo.setObjectName("targetCombo")
        self.horizontalLayout_6.addWidget(self.targetCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 3, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(self.bugDetailsBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.assignedCombo = QtGui.QComboBox(self.bugDetailsBox)
        self.assignedCombo.setObjectName("assignedCombo")
        self.horizontalLayout_7.addWidget(self.assignedCombo)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 3, 4, 1, 2)
        self.label_11 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 3, 1, 1)
        self.reporterLabel = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.reporterLabel.setFont(font)
        self.reporterLabel.setText("")
        self.reporterLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.reporterLabel.setObjectName("reporterLabel")
        self.gridLayout_2.addWidget(self.reporterLabel, 2, 4, 1, 2)
        self.creatorLabel = QtGui.QLabel(self.bugDetailsBox)
        self.creatorLabel.setText("")
        self.creatorLabel.setObjectName("creatorLabel")
        self.gridLayout_2.addWidget(self.creatorLabel, 1, 4, 1, 2)
        self.label_2 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.bugDetailsBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.createdLabel = QtGui.QLabel(self.bugDetailsBox)
        self.createdLabel.setText("")
        self.createdLabel.setObjectName("createdLabel")
        self.gridLayout_2.addWidget(self.createdLabel, 1, 2, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.saveDetailsButton = QtGui.QPushButton(self.bugDetailsBox)
        self.saveDetailsButton.setObjectName("saveDetailsButton")
        self.horizontalLayout_10.addWidget(self.saveDetailsButton)
        self.discardDetailsButton = QtGui.QPushButton(self.bugDetailsBox)
        self.discardDetailsButton.setObjectName("discardDetailsButton")
        self.horizontalLayout_10.addWidget(self.discardDetailsButton)
        self.updateAllButton = QtGui.QPushButton(self.bugDetailsBox)
        self.updateAllButton.setEnabled(False)
        self.updateAllButton.setObjectName("updateAllButton")
        self.horizontalLayout_10.addWidget(self.updateAllButton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.addCommentButton = QtGui.QPushButton(self.bugDetailsBox)
        self.addCommentButton.setEnabled(False)
        self.addCommentButton.setCheckable(True)
        self.addCommentButton.setChecked(False)
        self.addCommentButton.setDefault(False)
        self.addCommentButton.setFlat(False)
        self.addCommentButton.setObjectName("addCommentButton")
        self.horizontalLayout_10.addWidget(self.addCommentButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 4, 1, 1, 5)
        self.verticalLayout_2.addWidget(self.bugDetailsBox)
        self.newCommentBox = QtGui.QGroupBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.newCommentBox.setFont(font)
        self.newCommentBox.setObjectName("newCommentBox")
        self.newCommentGrid = QtGui.QGridLayout(self.newCommentBox)
        self.newCommentGrid.setObjectName("newCommentGrid")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.newCommentGrid.addItem(spacerItem7, 1, 0, 1, 1)
        self.saveCommentButton = QtGui.QPushButton(self.newCommentBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.saveCommentButton.setFont(font)
        self.saveCommentButton.setObjectName("saveCommentButton")
        self.newCommentGrid.addWidget(self.saveCommentButton, 1, 2, 1, 1)
        self.newCommentEdit = QtGui.QTextEdit(self.newCommentBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.newCommentEdit.setFont(font)
        self.newCommentEdit.setObjectName("newCommentEdit")
        self.newCommentGrid.addWidget(self.newCommentEdit, 0, 0, 1, 3)
        self.cancelComment = QtGui.QPushButton(self.newCommentBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.cancelComment.setFont(font)
        self.cancelComment.setObjectName("cancelComment")
        self.newCommentGrid.addWidget(self.cancelComment, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.newCommentBox)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.mainBox, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.actionA_bout = QtGui.QAction(MainWindow)
        self.actionA_bout.setObjectName("actionA_bout")
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Close)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menu_Help.addAction(self.actionA_bout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Quit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.addCommentButton, QtCore.SIGNAL("toggled(bool)"), self.newCommentBox.setVisible)
        QtCore.QObject.connect(self.addCommentButton, QtCore.SIGNAL("toggled(bool)"), self.bugDetailsBox.setHidden)
        QtCore.QObject.connect(self.cancelComment, QtCore.SIGNAL("clicked()"), self.addCommentButton.toggle)
        QtCore.QObject.connect(self.addCommentButton, QtCore.SIGNAL("clicked()"), self.newCommentEdit.setFocus)
        QtCore.QObject.connect(self.newBugButton, QtCore.SIGNAL("toggled(bool)"), self.newBugBox.setVisible)
        QtCore.QObject.connect(self.newBugEdit, QtCore.SIGNAL("returnPressed()"), self.saveBugButton.click)
        QtCore.QObject.connect(self.newBugButton, QtCore.SIGNAL("clicked()"), self.newBugEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.bugTable, self.newBugEdit)
        MainWindow.setTabOrder(self.newBugEdit, self.saveBugButton)
        MainWindow.setTabOrder(self.saveBugButton, self.bugCommentBrowser)
        MainWindow.setTabOrder(self.bugCommentBrowser, self.statusCombo)
        MainWindow.setTabOrder(self.statusCombo, self.severityCombo)
        MainWindow.setTabOrder(self.severityCombo, self.targetCombo)
        MainWindow.setTabOrder(self.targetCombo, self.assignedCombo)
        MainWindow.setTabOrder(self.assignedCombo, self.newCommentEdit)
        MainWindow.setTabOrder(self.newCommentEdit, self.saveCommentButton)
        MainWindow.setTabOrder(self.saveCommentButton, self.cancelComment)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Qt Bugs Everywhere", None, QtGui.QApplication.UnicodeUTF8))
        self.projectTitle.setText(QtGui.QApplication.translate("MainWindow", "Project Title", None, QtGui.QApplication.UnicodeUTF8))
        self.newBugBox.setTitle(QtGui.QApplication.translate("MainWindow", "Create Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBugButton.setText(QtGui.QApplication.translate("MainWindow", "Save Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.bugsLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Showing", None, QtGui.QApplication.UnicodeUTF8))
        self.bugsLabel.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.bugFilterCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "active", None, QtGui.QApplication.UnicodeUTF8))
        self.bugFilterCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "inactive", None, QtGui.QApplication.UnicodeUTF8))
        self.bugFilterCombo.setItemText(2, QtGui.QApplication.translate("MainWindow", "custom", None, QtGui.QApplication.UnicodeUTF8))
        self.bugsLabel_2.setText(QtGui.QApplication.translate("MainWindow", "bugs", None, QtGui.QApplication.UnicodeUTF8))
        self.newBugButton.setText(QtGui.QApplication.translate("MainWindow", "New Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.removeBugButton.setText(QtGui.QApplication.translate("MainWindow", "Remove Bug", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Version Control:", None, QtGui.QApplication.UnicodeUTF8))
        self.customFilterLabel.setText(QtGui.QApplication.translate("MainWindow", "Select Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.propertyCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "status", None, QtGui.QApplication.UnicodeUTF8))
        self.propertyCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "severity", None, QtGui.QApplication.UnicodeUTF8))
        self.propertyCombo.setItemText(2, QtGui.QApplication.translate("MainWindow", "target", None, QtGui.QApplication.UnicodeUTF8))
        self.propertyCombo.setItemText(3, QtGui.QApplication.translate("MainWindow", "assigned", None, QtGui.QApplication.UnicodeUTF8))
        self.addFilterButton.setText(QtGui.QApplication.translate("MainWindow", "Add Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterBugsButton.setText(QtGui.QApplication.translate("MainWindow", "Filter Bugs", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelFilterButton.setText(QtGui.QApplication.translate("MainWindow", "Clear Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.bugTitle.setText(QtGui.QApplication.translate("MainWindow", "Bug Title", None, QtGui.QApplication.UnicodeUTF8))
        self.bugDetailsBox.setTitle(QtGui.QApplication.translate("MainWindow", "Bug Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Short Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Severity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Assigned", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Reporter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Creator:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Created at:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDetailsButton.setText(QtGui.QApplication.translate("MainWindow", "Save Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.discardDetailsButton.setText(QtGui.QApplication.translate("MainWindow", "Discard Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.updateAllButton.setText(QtGui.QApplication.translate("MainWindow", "Update All", None, QtGui.QApplication.UnicodeUTF8))
        self.addCommentButton.setText(QtGui.QApplication.translate("MainWindow", "Add Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.newCommentBox.setTitle(QtGui.QApplication.translate("MainWindow", "Add New Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.saveCommentButton.setText(QtGui.QApplication.translate("MainWindow", "Save Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelComment.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">No project is open.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Please create a new project</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">or open an exisiting project</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">to view/edit/track your bugs.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA_bout.setText(QtGui.QApplication.translate("MainWindow", "A&bout", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))

